# This workflow will run unit test.

name: unit test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Linting
        run: flake8 ./
      - name: unit test
        run: pytest tests
      - name: run linear_toy_demo
        run: python examples/linear_toy/linear_toy_demo.py
      - name: run linear_toy_w_input_limits_demo
        run: python examples/linear_toy/linear_toy_w_input_limits_demo.py
      - name: run nonlinear_toy_demo
        run: python examples/nonlinear_toy/demo.py
      - name: run nonlinear toy demo_trigpoly
        run: python examples/nonlinear_toy/demo_trigpoly.py --unit_test
